# Этап 1: Сборка React приложения
FROM node:20-alpine as build-stage

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Этап 2: Раздача статики через Nginx
FROM nginx:stable-alpine

# Копируем билд из предыдущего этапа
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Копируем конфиг Nginx (необязательно, но полезно для SPA)
# Мы создадим его ниже
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]