# Изолированный образ для бэкенда
FROM node:20-alpine

WORKDIR /app

# Копируем зависимости бэкенда
COPY package*.json ./
RUN npm install

# Копируем исходный код сервера
COPY server.js config.json ./

# Создаем папки, которые указаны в стандартном конфиге (на случай, если их нет)
RUN mkdir -p test_folder logs

EXPOSE 3001

CMD ["node", "server.js"]